if (NOT STM32BlueNRG_DIR)
    message(WARNING "STM32BlueNRG_DIR not set, using ${STM32Cube_DIR}")
    set(STM32BlueNRG_DIR ${STM32Cube_DIR})
endif()

if (NOT STM32BlueNRG_HAL_DIR)
    message(WARNING "STM32BlueNRG_HAL_DIR not set, using ${STM32BlueNRG_DIR}")
    set(STM32BlueNRG_HAL_DIR ${STM32BlueNRG_DIR})
endif()
set(BLUENRG_HAL_PREFIX "STM32${STM32_FAMILY}xx_HAL_BlueNRG")
STRING(TOLOWER ${BLUENRG_HAL_PREFIX} BLUENRG_HAL_PREFIX_LOWER)

set(BLUENRG_HAL_SRCS
        ${BLUENRG_HAL_PREFIX}_Drivers/src/${BLUENRG_HAL_PREFIX_LOWER}_spi.c)
set(BLUENRG_HAL_HEADERS
        ${BLUENRG_HAL_PREFIX}_Drivers/inc/${BLUENRG_HAL_PREFIX_LOWER}_spi.h)

set(BLUENRG_SRCS
        ${BLUENRG_HAL_SRCS}
        SimpleBlueNRG_HCI/hci/hci.c

        SimpleBlueNRG_HCI/hci/controller/bluenrg_gap_aci.c
        SimpleBlueNRG_HCI/hci/controller/bluenrg_gatt_aci.c
        SimpleBlueNRG_HCI/hci/controller/bluenrg_hal_aci.c
        SimpleBlueNRG_HCI/hci/controller/bluenrg_l2cap_aci.c
        SimpleBlueNRG_HCI/hci/controller/bluenrg_updater_aci.c

        SimpleBlueNRG_HCI/utils/gp_timer.c
        SimpleBlueNRG_HCI/utils/list.c
        SimpleBlueNRG_HCI/utils/osal.c
        )

set(BLUENRG_HEADERS
        ${BLUENRG_HAL_HEADERS}
        SimpleBlueNRG_HCI/includes/bluenrg_aci.h

        )

STRING(TOLOWER ${STM32_FAMILY} STM32_FAMILY_LOWER)

FOREACH(BLUENRG_INC ${BLUENRG_HEADERS})
    SET(BLUENRG_${BLUENRG_INC}_FILE BLUENRG_${BLUENRG_INC}_FILE-NOTFOUND)
    SET(BLUENRG_${BLUENRG_INC}_PATH BLUENRG_${BLUENRG_INC}_PATH-NOTFOUND)
    FIND_FILE(BLUENRG_${BLUENRG_INC}_FILE ${BLUENRG_INC}
            PATH_SUFFIXES Middlewares/ST/STM32_BlueNRG ST/STM32_BlueNRG STM32_BlueNRG
            HINTS ${STM32BlueNRG_DIR} ${STM32BlueNRG_HAL_DIR}
            CMAKE_FIND_ROOT_PATH_BOTH
            )

    IF (BLUENRG_${BLUENRG_INC}_FILE STREQUAL "BLUENRG_${BLUENRG_INC}_FILE-NOTFOUND")
        MESSAGE(WARNING "NOT FOUND ${BLUENRG_INC}")
    ELSE()
        GET_FILENAME_COMPONENT(BLUENRG_${BLUENRG_INC}_PATH ${BLUENRG_${BLUENRG_INC}_FILE} DIRECTORY)
    ENDIF()
    LIST(APPEND STM32BlueNRG_INCLUDE_DIR ${BLUENRG_${BLUENRG_INC}_PATH})
ENDFOREACH()
LIST(REMOVE_DUPLICATES STM32USB_INCLUDE_DIR)

FOREACH(BLUENRG_SRC ${BLUENRG_SRCS})
    SET(BLUENRG_${BLUENRG_SRC}_FILE BLUENRG_${BLUENRG_SRC}_FILE-NOTFOUND)
    FIND_FILE(BLUENRG_${BLUENRG_SRC}_FILE ${BLUENRG_SRC}
            PATH_SUFFIXES Middlewares/ST/STM32_BlueNRG ST/STM32_BlueNRG STM32_BlueNRG
            HINTS ${STM32BlueNRG_DIR} ${STM32BlueNRG_HAL_DIR}
            CMAKE_FIND_ROOT_PATH_BOTH
            )
    LIST(APPEND STM32BlueNRG_SOURCES ${BLUENRG_${BLUENRG_SRC}_FILE})
    MESSAGE(WARNING "File: ${BLUENRG_${BLUENRG_SRC}_FILE}")
ENDFOREACH()
INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(STM32BLUENRG DEFAULT_MSG STM32BlueNRG_INCLUDE_DIR STM32BlueNRG_SOURCES)
