SET(USB_CLASSES AUDIO CDC CustomHID DFU HID MSC)

SET(USB_PREFIX usbd_)

SET(USB_HEADERS
        Core/Inc/usbd_def.h
        Core/Inc/usbd_core.h
        Core/Inc/usbd_ctlreq.h
        Core/Inc/usbd_ioreq.h
)

SET(USB_INCLUDE_DIR
        Core/Inc
)
SET(USB_SRCS
    Core/Src/usbd_core.c
    Core/Src/usbd_ctlreq.c
    Core/Src/usbd_ioreq.c
)

IF(NOT STM32USB_FIND_COMPONENTS)
    SET(STM32USB_FIND_COMPONENTS ${USB_CLASSES})
    MESSAGE(WARNING "No STM32USB classes selected, using only core")
ENDIF()

FOREACH(cmp ${STM32USB_FIND_COMPONENTS})
    LIST(FIND STM32USB_FIND_COMPONENTS ${cmp} STM32USB_FOUND_INDEX)
    IF(${STM32USB_FOUND_INDEX} LESS 0)
        LIST(APPEND STM32USB_FIND_COMPONENTS ${cmp})
    ENDIF()
ENDFOREACH()

FOREACH(cmp ${STM32USB_FIND_COMPONENTS})
    LIST(FIND USB_CLASSES ${cmp} STM32USB_FOUND_INDEX)
    IF(${STM32USB_FOUND_INDEX} LESS 0)
        MESSAGE(FATAL_ERROR "Unknown STM32USB class: ${cmp}. Available classes: ${USB_CLASSES}")
    ENDIF()
	STRING(TOLOWER ${cmp} cmp_lower)	
    IF(NOT (${STM32USB_FOUND_INDEX} LESS 0))
        LIST(APPEND USB_HEADERS Class/${cmp}/Inc/${USB_PREFIX}${cmp_lower}.h) #        LIST(APPEND USB_DIRS Class/${cmp}/Inc)
        LIST(APPEND USB_SRCS Class/${cmp}/Src/${USB_PREFIX}${cmp_lower}.c)
    ENDIF()
ENDFOREACH()

LIST(REMOVE_DUPLICATES USB_HEADERS)
LIST(REMOVE_DUPLICATES USB_SRCS)

STRING(TOLOWER ${STM32_FAMILY} STM32_FAMILY_LOWER)

FIND_PATH(STM32USB_INCLUDE_DIR ${USB_HEADERS}
        HINTS ${STM32Cube_DIR}/Middlewares/ST/STM32_USB_Device_Library
        CMAKE_FIND_ROOT_PATH_BOTH
)


FOREACH(USB_INC ${USB_HEADERS})
    SET(USB_${USB_INC}_FILE USB_${USB_INC}_FILE-NOTFOUND)
    SET(USB_${USB_INC}_PATH USB_${USB_INC}_PATH-NOTFOUND)
    FIND_FILE(USB_${USB_INC}_FILE ${USB_INC}
            HINTS ${STM32Cube_DIR}/Middlewares/ST/STM32_USB_Device_Library
            CMAKE_FIND_ROOT_PATH_BOTH
            )

    IF (USB_${USB_INC}_FILE STREQUAL "USB_${USB_INC}_FILE-NOTFOUND")
            MESSAGE(WARNING "NOT FOUND ${USB_INC}")
        ELSE()
            GET_FILENAME_COMPONENT(USB_${USB_INC}_PATH ${USB_${USB_INC}_FILE} DIRECTORY)
    ENDIF()
    LIST(APPEND STM32USB_INCLUDE_DIR ${USB_${USB_INC}_PATH})
ENDFOREACH()
LIST(REMOVE_DUPLICATES STM32USB_INCLUDE_DIR)
FOREACH(USB_SRC ${USB_SRCS})
    SET(USB_${USB_SRC}_FILE USB_${USB_SRC}_FILE-NOTFOUND)
    FIND_FILE(USB_${USB_SRC}_FILE ${USB_SRC}
            HINTS ${STM32Cube_DIR}/Middlewares/ST/STM32_USB_Device_Library
            CMAKE_FIND_ROOT_PATH_BOTH
            )
    LIST(APPEND STM32USB_SOURCES ${USB_${USB_SRC}_FILE})
ENDFOREACH()
INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(STM32USB DEFAULT_MSG STM32USB_INCLUDE_DIR STM32USB_SOURCES)
