name: Tests

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        family: [F0, F1, F2, F3, F4, F7, G0, G4, H7, L0, L1, L4, L5, U5, WB, WL, MP1]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      
    - name: Install ARM toolchain
      run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi 

    - name: Test fetch
      shell: bash
      run: |
          cmake -DTEST_FAMILIES=${{ matrix.family }} -S $GITHUB_WORKSPACE/tests/fetch/ -B ${{runner.workspace}}/tests/fetch/build
          cmake --build ${{runner.workspace}}/tests/fetch/build --config $BUILD_TYPE --

    - name: Test HAL
      shell: bash
      run: |
          cmake -DTEST_FAMILIES=${{ matrix.family }} -DFETCH_ST_SOURCES=TRUE -S $GITHUB_WORKSPACE/tests/hal/ -B ${{runner.workspace}}/tests/hal/build
          cmake --build ${{runner.workspace}}/tests/hal/build --config $BUILD_TYPE --


    - name: Test CMSIS
      shell: bash
      run: |
          cmake -DTEST_FAMILIES=${{ matrix.family }} -DFETCH_ST_SOURCES=TRUE -S $GITHUB_WORKSPACE/tests/cmsis/ -B ${{runner.workspace}}/tests/cmsis/build
          cmake --build ${{runner.workspace}}/tests/cmsis/build --config $BUILD_TYPE --
      if: ${{ matrix.family != 'MP1' }}
