name: Tests

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  test-ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        family: [F0, F1, F2, F3, F4, F7, G0, G4, H7, L0, L1, L4, L5, U5, WB, WL, MP1]

    steps:
    - uses: actions/checkout@v2
      
    - name: Install ARM toolchain
      run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi 

    - name: Test fetch
      working-directory: $GITHUB_WORKSPACE/tests/fetch
      run: |
          cmake -DTEST_FAMILIES=${{ matrix.family }} -B build --log-level=TRACE
          cmake --build build --config $BUILD_TYPE --

    - name: Test HAL
      working-directory: $GITHUB_WORKSPACE/tests/hal
      run: |
          cmake -DTEST_FAMILIES=${{ matrix.family }} -DSTM32_CUBE_${{matrix.family}}_PATH=$GITHUB_WORKSPACE/tests/fetch/.deps/stm32-hal-f0-src -B build --log-level=TRACE
          cmake --build build --config $BUILD_TYPE --


    - name: Test CMSIS
      working-directory: $GITHUB_WORKSPACE/tests/cmsis
      if: ${{ matrix.family != 'MP1' }}
      run: |
          cmake -DTEST_FAMILIES=${{ matrix.family }} -DSTM32_CUBE_${{matrix.family}}_PATH=$GITHUB_WORKSPACE/tests/fetch/.deps/stm32-cmsis-f0-src -B build --log-level=TRACE
          cmake --build build --config $BUILD_TYPE --
